=== openpatch/hyperbook/packages/vscode-extension/schemas/hyperbook.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "properties": {
    "author": {
      "properties": {
        "name": {
          "type": "string"
        },
        "url": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "basePath": {
      "type": "string"
    },
    "colors": {
      "properties": {
        "brand": {
          "format": "color-hex",
          "type": "string"
        },
        "brandDark": {
          "format": "color-hex",
          "type": "string"
        },
        "brandText": {
          "format": "color-hex",
          "type": "string"
        }
      },
      "type": "object"
    },
    "description": {
      "type": "string"
    },
    "font": {
      "type": "string"
    },
    "fonts": {
      "properties": {
        "body": {
          "type": "string"
        },
        "code": {
          "type": "string"
        },
        "heading": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "language": {
      "enum": ["de", "en", "es", "fr"],
      "type": "string"
    },
    "license": {
      "type": "string"
    },
    "logo": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "repo": {
      "type": "string"
    },
    "template": {
      "type": "string"
    }
  },
  "required": ["name"],
  "type": "object"
}

=== openpatch/hyperbook/website/hyperbook.json
{
  "name": "Hyperbook Documentation",
  "description": "Documentation for Hyperbook created with Hyperbook",
  "author": {
    "name": "OpenPatch",
    "url": "https://openpatch.org"
  },
  "fonts": {
    "heading": "/fonts/Montserrat-VariableFont_wght.ttf",
    "body": "/fonts/Montserrat-VariableFont_wght.ttf",
    "code": "/fonts/FiraCode-Regular.woff2"
  },
  "language": "en",
  "logo": "/logo.svg",
  "repo": "https://github.com/openpatch/hyperbook/edit/main/website"
}
